-- ─── Taxonomie-Datenbank Seed ────────────────────────────────────────────────
-- Verifizierte Arten für KI-Bestimmungs-Whitelist.
-- Quellen: POWO (Kew Gardens), WFO, GBIF, FishBase
-- Alle wissenschaftlichen Namen gemäß aktueller Taxonomie (Stand 2024).

-- ─── ALOCASIA (30 Arten/Sorten) ──────────────────────────────────────────────
INSERT INTO taxonomy_species (scientificName, cultivar, genus, family, commonNames, synonyms, keyFeatures, habitat, careLevel, light, water, category, source, verified) VALUES
('Alocasia baginda', 'Dragon Scale', 'Alocasia', 'Araceae',
  '{"de": "Drachenschuppen-Alocasia", "en": "Dragon Scale Alocasia"}',
  '["Alocasia sp. Dragon Scale", "Alocasia baginda Dragon Scale"]',
  '["silbrig-grüne Blattoberfläche mit Schuppenstruktur", "ausgeprägte dunkelgrüne Nervatur", "kompakter Wuchs", "matte Blattoberfläche", "Blattunterseite hellgrün bis silbrig"]',
  'Tropischer Regenwald, Borneo (Malaysia)', 'mittel', 'hell, kein direktes Sonnenlicht', 'mäßig, Substrat leicht feucht halten',
  'alocasia', 'POWO', true),

('Alocasia baginda', 'Silver Dragon', 'Alocasia', 'Araceae',
  '{"de": "Silberdrachen-Alocasia", "en": "Silver Dragon Alocasia"}',
  '["Alocasia baginda Silver Dragon"]',
  '["silbrig-hellgrüne Blattoberfläche", "weniger ausgeprägte Nervatur als Dragon Scale", "kompakter als Dragon Scale", "silbrig schimmernde Blattfläche"]',
  'Tropischer Regenwald, Borneo (Malaysia)', 'mittel', 'hell, kein direktes Sonnenlicht', 'mäßig',
  'alocasia', 'POWO', true),

('Alocasia zebrina', NULL, 'Alocasia', 'Araceae',
  '{"de": "Zebra-Alocasia", "en": "Zebra Elephant Ear"}',
  '["Alocasia zebrina var. zebrina"]',
  '["auffällig gestreifter Blattstiel (schwarz-grün wie Zebra)", "pfeilförmige Blätter", "aufrechter Wuchs", "glänzende Blattoberfläche"]',
  'Philippinen, tropischer Regenwald', 'mittel', 'hell bis halbschattig', 'regelmäßig',
  'alocasia', 'POWO', true),

('Alocasia amazonica', 'Polly', 'Alocasia', 'Araceae',
  '{"de": "Amazonica Polly", "en": "African Mask Plant"}',
  '["Alocasia x amazonica", "Alocasia Polly"]',
  '["dunkelgrüne Blätter mit weißen/cremefarbenen Blattadern", "gewellter Blattrand", "kompakter Wuchs", "Hybride aus Alocasia longiloba x Alocasia sanderiana"]',
  'Züchtung (Hybride)', 'mittel', 'hell, kein direktes Sonnenlicht', 'regelmäßig, Staunässe vermeiden',
  'alocasia', 'POWO', true),

('Alocasia macrorrhizos', NULL, 'Alocasia', 'Araceae',
  '{"de": "Riesenaronstab", "en": "Giant Taro"}',
  '["Alocasia macrorrhiza", "Colocasia macrorrhizos"]',
  '["sehr große pfeilförmige Blätter bis 1,5m", "aufrechter Blattstiel", "glänzende Blattoberfläche", "kräftiger Stamm"]',
  'Tropisches Asien, Pazifik', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'alocasia', 'POWO', true),

('Alocasia longiloba', NULL, 'Alocasia', 'Araceae',
  '{"de": "Langlappige Alocasia", "en": "Longiloba Elephant Ear"}',
  '["Alocasia longiloba var. longiloba"]',
  '["schmale lanzettliche Blätter", "silbrig-grüne Blattoberfläche", "ausgeprägte Nervatur", "aufrechter Wuchs"]',
  'Südostasien, Borneo, Malaysia', 'mittel', 'hell bis halbschattig', 'mäßig',
  'alocasia', 'POWO', true),

('Alocasia cuprea', NULL, 'Alocasia', 'Araceae',
  '{"de": "Kupfer-Alocasia", "en": "Mirror Plant, Jewel Alocasia"}',
  '["Alocasia cuprea var. cuprea"]',
  '["kupfrig-metallische Blattoberfläche", "dunkelgrüne bis schwarze Blattadern", "kompakter Wuchs", "Blattunterseite tief violett-lila"]',
  'Borneo (Malaysia, Sarawak)', 'anspruchsvoll', 'hell, kein direktes Sonnenlicht', 'mäßig, hohe Luftfeuchtigkeit',
  'alocasia', 'POWO', true),

('Alocasia reginula', 'Black Velvet', 'Alocasia', 'Araceae',
  '{"de": "Schwarzer Samt", "en": "Black Velvet Alocasia"}',
  '["Alocasia reginula Black Velvet", "Alocasia Black Velvet"]',
  '["dunkelgrüne bis fast schwarze Blätter", "samtige Blattoberfläche", "weiße Blattadern", "kompakter Zwergwuchs", "Jewel Alocasia"]',
  'Borneo', 'anspruchsvoll', 'hell, kein direktes Sonnenlicht', 'mäßig, hohe Luftfeuchtigkeit',
  'alocasia', 'POWO', true),

('Alocasia maharani', NULL, 'Alocasia', 'Araceae',
  '{"de": "Maharani Alocasia", "en": "Grey Dragon Alocasia"}',
  '["Alocasia maharani Grey Dragon"]',
  '["grau-grüne strukturierte Blattoberfläche", "ausgeprägte Nervatur", "kompakter Wuchs", "Hybride"]',
  'Züchtung (Hybride)', 'mittel', 'hell', 'mäßig',
  'alocasia', 'manual', true),

('Alocasia micholitziana', 'Frydek', 'Alocasia', 'Araceae',
  '{"de": "Frydek Alocasia, Grüner Samt", "en": "Green Velvet Alocasia"}',
  '["Alocasia frydek", "Alocasia micholitziana Frydek"]',
  '["dunkelgrüne samtige Blattoberfläche", "weiße Blattadern", "pfeilförmige Blätter", "aufrechter Wuchs", "KEIN Variegata-Muster bei Normalform"]',
  'Philippinen', 'mittel', 'hell bis halbschattig', 'regelmäßig',
  'alocasia', 'POWO', true),

('Alocasia wentii', NULL, 'Alocasia', 'Araceae',
  '{"de": "Wentii Alocasia", "en": "Hardy Elephant Ear"}',
  '[]',
  '["große pfeilförmige Blätter", "Blattunterseite purpurviolett", "robuste Art", "aufrechter Wuchs"]',
  'Papua-Neuguinea', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'alocasia', 'POWO', true),

('Alocasia lauterbachiana', NULL, 'Alocasia', 'Araceae',
  '{"de": "Lauterbachs Alocasia", "en": "Purple Sword Alocasia"}',
  '[]',
  '["schmale lanzettliche Blätter", "gewellter Blattrand", "Blattunterseite purpurviolett", "aufrechter Wuchs"]',
  'Papua-Neuguinea', 'mittel', 'hell', 'regelmäßig',
  'alocasia', 'POWO', true),

('Alocasia sanderiana', NULL, 'Alocasia', 'Araceae',
  '{"de": "Sanders Alocasia, Kris Plant", "en": "Kris Plant"}',
  '["Alocasia sanderiana var. sanderiana"]',
  '["tief eingeschnittener Blattrand (Kris-Schwert-Form)", "dunkelgrüne Blätter", "silbrig-weiße Blattadern", "aufrechter Wuchs"]',
  'Philippinen (Mindanao)', 'anspruchsvoll', 'hell', 'mäßig, hohe Luftfeuchtigkeit',
  'alocasia', 'POWO', true),

('Alocasia melo', NULL, 'Alocasia', 'Araceae',
  '{"de": "Melo Alocasia", "en": "Melo Elephant Ear"}',
  '[]',
  '["extrem dicke, fast sukkulente Blätter", "stark strukturierte Blattoberfläche", "grau-grüne Farbe", "kompakter Wuchs"]',
  'Borneo', 'anspruchsvoll', 'hell', 'wenig, Substrat fast trocken',
  'alocasia', 'POWO', true),

('Alocasia scalprum', NULL, 'Alocasia', 'Araceae',
  '{"de": "Skalpell-Alocasia", "en": "Scalprum Elephant Ear"}',
  '[]',
  '["schmale lanzettliche Blätter", "ledrige Blattstruktur", "dunkelgrüne Farbe", "aufrechter Wuchs"]',
  'Philippinen', 'mittel', 'hell', 'mäßig',
  'alocasia', 'POWO', true),

('Alocasia sinuata', NULL, 'Alocasia', 'Araceae',
  '{"de": "Gewellte Alocasia", "en": "Quilted Dreams Alocasia"}',
  '[]',
  '["stark strukturierte, wellige Blattoberfläche", "dunkelgrüne Farbe", "kompakter Wuchs", "Jewel Alocasia"]',
  'Philippinen', 'anspruchsvoll', 'hell', 'mäßig, hohe Luftfeuchtigkeit',
  'alocasia', 'POWO', true),

('Alocasia nebula', NULL, 'Alocasia', 'Araceae',
  '{"de": "Nebula Alocasia", "en": "Nebula Elephant Ear"}',
  '["Alocasia nebula Imperialis"]',
  '["silbrig-grüne Blattoberfläche", "ausgeprägte Nervatur", "kompakter Wuchs", "Jewel Alocasia"]',
  'Borneo', 'anspruchsvoll', 'hell', 'mäßig, hohe Luftfeuchtigkeit',
  'alocasia', 'POWO', true),

('Alocasia azlanii', NULL, 'Alocasia', 'Araceae',
  '{"de": "Azlanii Alocasia", "en": "Red Mambo Alocasia"}',
  '[]',
  '["metallisch-grüne Blattoberfläche", "rote bis violette Blattadern", "Blattunterseite tief violett", "kompakter Wuchs"]',
  'Borneo (Malaysia)', 'anspruchsvoll', 'hell', 'mäßig, hohe Luftfeuchtigkeit',
  'alocasia', 'POWO', true),

('Alocasia infernalis', NULL, 'Alocasia', 'Araceae',
  '{"de": "Schwarze Magie Alocasia", "en": "Black Magic Alocasia"}',
  '["Alocasia infernalis Black Magic"]',
  '["fast schwarze Blattoberfläche", "metallischer Glanz", "kompakter Wuchs", "Jewel Alocasia"]',
  'Borneo (Malaysia, Sabah)', 'anspruchsvoll', 'hell', 'mäßig, hohe Luftfeuchtigkeit',
  'alocasia', 'POWO', true),

('Alocasia heterophylla', NULL, 'Alocasia', 'Araceae',
  '{"de": "Verschiedenblättrige Alocasia", "en": "Heterophylla Elephant Ear"}',
  '["Alocasia heterophylla Dragons Breath"]',
  '["schmale lanzettliche Blätter", "aufrechter Wuchs", "grüne Blattfarbe", "variabel geformte Blätter"]',
  'Australien, Neuguinea', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'alocasia', 'POWO', true),

('Alocasia jacklyn', NULL, 'Alocasia', 'Araceae',
  '{"de": "Jacklyn Alocasia", "en": "Jacklyn Elephant Ear"}',
  '[]',
  '["tief eingeschnittene Blätter", "dunkelgrüne Farbe", "ausgeprägte Nervatur", "aufrechter Wuchs"]',
  'Papua-Neuguinea', 'mittel', 'hell', 'regelmäßig',
  'alocasia', 'manual', true),

('Alocasia stingray', NULL, 'Alocasia', 'Araceae',
  '{"de": "Stachelrochen-Alocasia", "en": "Stingray Alocasia"}',
  '["Alocasia macrorrhizos Stingray"]',
  '["Blattspreite mit langer Spitze (Stachelrochen-Form)", "aufrechter Blattstiel", "grüne Farbe"]',
  'Züchtung', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'alocasia', 'manual', true),

('Alocasia watsoniana', NULL, 'Alocasia', 'Araceae',
  '{"de": "Watsons Alocasia", "en": "Watson Elephant Ear"}',
  '[]',
  '["große Blätter mit silbrig-grüner Oberfläche", "ausgeprägte Nervatur", "aufrechter Wuchs"]',
  'Borneo', 'mittel', 'hell', 'regelmäßig',
  'alocasia', 'POWO', true),

('Alocasia odora', NULL, 'Alocasia', 'Araceae',
  '{"de": "Duftende Alocasia", "en": "Night-scented Lily"}',
  '["Alocasia odora var. odora"]',
  '["sehr große Blätter", "aufrechter Wuchs", "duftende Blüten", "robuste Art"]',
  'Ostasien (China, Japan, Korea)', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'alocasia', 'POWO', true),

('Alocasia clypeolata', NULL, 'Alocasia', 'Araceae',
  '{"de": "Schildförmige Alocasia", "en": "Green Shield Alocasia"}',
  '[]',
  '["schildförmige Blätter", "grüne Farbe", "kompakter Wuchs"]',
  'Philippinen', 'mittel', 'hell', 'mäßig',
  'alocasia', 'POWO', true),

('Alocasia reversa', NULL, 'Alocasia', 'Araceae',
  '{"de": "Umgekehrte Alocasia", "en": "Reversa Elephant Ear"}',
  '[]',
  '["ungewöhnliche Blattform", "dunkelgrüne Farbe", "kompakter Wuchs"]',
  'Borneo', 'anspruchsvoll', 'hell', 'mäßig, hohe Luftfeuchtigkeit',
  'alocasia', 'POWO', true),

('Alocasia reginae', NULL, 'Alocasia', 'Araceae',
  '{"de": "Königin-Alocasia", "en": "Queen Alocasia"}',
  '[]',
  '["metallisch-grüne Blattoberfläche", "kompakter Wuchs", "Jewel Alocasia"]',
  'Borneo', 'anspruchsvoll', 'hell', 'mäßig, hohe Luftfeuchtigkeit',
  'alocasia', 'POWO', true),

('Alocasia princeps', NULL, 'Alocasia', 'Araceae',
  '{"de": "Prinz-Alocasia", "en": "Purple Cloak Alocasia"}',
  '[]',
  '["dunkelgrüne bis fast schwarze Blätter", "Blattunterseite violett", "kompakter Wuchs"]',
  'Borneo', 'anspruchsvoll', 'hell', 'mäßig, hohe Luftfeuchtigkeit',
  'alocasia', 'POWO', true),

('Alocasia portei', NULL, 'Alocasia', 'Araceae',
  '{"de": "Portes Alocasia", "en": "Portei Elephant Ear"}',
  '[]',
  '["tief eingeschnittene Blätter", "aufrechter Wuchs", "große Blätter"]',
  'Philippinen', 'mittel', 'hell bis halbschattig', 'regelmäßig',
  'alocasia', 'POWO', true),

('Alocasia brancifolia', NULL, 'Alocasia', 'Araceae',
  '{"de": "Brancifolia Alocasia", "en": "Brancifolia Elephant Ear"}',
  '[]',
  '["tief eingeschnittene Blätter", "aufrechter Wuchs"]',
  'Australien', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'alocasia', 'POWO', true)

ON DUPLICATE KEY UPDATE verified = verified;

-- ─── PHILODENDRON (25 Arten/Sorten) ──────────────────────────────────────────
INSERT INTO taxonomy_species (scientificName, cultivar, genus, family, commonNames, synonyms, keyFeatures, habitat, careLevel, light, water, category, source, verified) VALUES
('Philodendron gloriosum', NULL, 'Philodendron', 'Araceae',
  '{"de": "Gloriosum Philodendron", "en": "Gloriosum Philodendron"}',
  '[]',
  '["samtige dunkelgrüne Blätter", "weiße/cremefarbene Blattadern", "kriechender Wuchs (terrestrisch)", "herzförmige Blätter", "Blätter werden sehr groß"]',
  'Kolumbien, tropischer Regenwald', 'mittel', 'hell bis halbschattig', 'regelmäßig, hohe Luftfeuchtigkeit',
  'philodendron', 'POWO', true),

('Philodendron melanochrysum', NULL, 'Philodendron', 'Araceae',
  '{"de": "Schwarzgold-Philodendron", "en": "Black Gold Philodendron"}',
  '["Philodendron andreanum"]',
  '["samtige dunkelgrüne Blätter", "goldene Blattadern", "kletternder Wuchs", "Blätter werden sehr lang"]',
  'Kolumbien, Ecuador', 'mittel', 'hell bis halbschattig', 'regelmäßig, hohe Luftfeuchtigkeit',
  'philodendron', 'POWO', true),

('Philodendron verrucosum', NULL, 'Philodendron', 'Araceae',
  '{"de": "Warziger Philodendron", "en": "Velvet Leaf Philodendron"}',
  '[]',
  '["samtige dunkelgrüne Blätter", "hellgrüne Blattadern", "rötliche Blattstiele mit Haaren", "kletternder Wuchs"]',
  'Costa Rica, Kolumbien, Ecuador, Peru', 'mittel', 'hell bis halbschattig', 'regelmäßig, hohe Luftfeuchtigkeit',
  'philodendron', 'POWO', true),

('Philodendron gloriosum x melanochrysum', 'Splendid', 'Philodendron', 'Araceae',
  '{"de": "Splendid Philodendron", "en": "Splendid Philodendron"}',
  '["Philodendron splendid"]',
  '["samtige Blätter", "Merkmale beider Elternteile", "kletternder Wuchs", "große Blätter"]',
  'Züchtung (Hybride)', 'mittel', 'hell bis halbschattig', 'regelmäßig',
  'philodendron', 'manual', true),

('Philodendron pedatum', 'Florida Beauty', 'Philodendron', 'Araceae',
  '{"de": "Florida Beauty Philodendron", "en": "Florida Beauty Philodendron"}',
  '["Philodendron florida beauty variegata"]',
  '["tief eingeschnittene Blätter", "variegierte Formen mit weißen/cremefarbenen Flecken", "kletternder Wuchs", "rote Blattstiele"]',
  'Züchtung', 'mittel', 'hell', 'regelmäßig',
  'philodendron', 'manual', true),

('Philodendron pedatum', 'Florida Ghost', 'Philodendron', 'Araceae',
  '{"de": "Florida Ghost Philodendron", "en": "Florida Ghost Philodendron"}',
  '[]',
  '["tief eingeschnittene Blätter", "junge Blätter fast weiß/mint", "kletternder Wuchs", "rote Blattstiele"]',
  'Züchtung', 'mittel', 'hell', 'regelmäßig',
  'philodendron', 'manual', true),

('Philodendron erubescens', 'Pink Princess', 'Philodendron', 'Araceae',
  '{"de": "Pink Princess Philodendron", "en": "Pink Princess Philodendron"}',
  '["Philodendron pink princess"]',
  '["dunkelgrüne bis fast schwarze Blätter", "rosa/pinke Panaschierung", "kletternder Wuchs", "rote Blattstiele"]',
  'Züchtung', 'mittel', 'hell', 'regelmäßig',
  'philodendron', 'manual', true),

('Philodendron erubescens', 'White Princess', 'Philodendron', 'Araceae',
  '{"de": "White Princess Philodendron", "en": "White Princess Philodendron"}',
  '[]',
  '["dunkelgrüne Blätter", "weiße Panaschierung", "kletternder Wuchs"]',
  'Züchtung', 'mittel', 'hell', 'regelmäßig',
  'philodendron', 'manual', true),

('Philodendron erubescens', 'White Wizard', 'Philodendron', 'Araceae',
  '{"de": "White Wizard Philodendron", "en": "White Wizard Philodendron"}',
  '[]',
  '["dunkelgrüne Blätter", "weiße Panaschierung", "grüne Blattstiele (Unterschied zu White Princess)", "kletternder Wuchs"]',
  'Züchtung', 'mittel', 'hell', 'regelmäßig',
  'philodendron', 'manual', true),

('Philodendron hederaceum', 'Birkin', 'Philodendron', 'Araceae',
  '{"de": "Birkin Philodendron", "en": "Birkin Philodendron"}',
  '["Philodendron birkin"]',
  '["dunkelgrüne Blätter mit weißen Streifen", "kompakter Wuchs", "aufrechter Wuchs"]',
  'Züchtung', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'philodendron', 'manual', true),

('Philodendron hederaceum', 'Brasil', 'Philodendron', 'Araceae',
  '{"de": "Brasil Philodendron", "en": "Brasil Philodendron"}',
  '["Philodendron brasil"]',
  '["grüne Blätter mit gelbem Mittelstreifen", "kletternder/hängender Wuchs", "herzförmige Blätter"]',
  'Züchtung', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'philodendron', 'manual', true),

('Philodendron hederaceum', 'Micans', 'Philodendron', 'Araceae',
  '{"de": "Micans Philodendron, Samtblatt", "en": "Velvet Leaf Philodendron"}',
  '["Philodendron micans"]',
  '["samtige bronzefarbene Blätter", "kletternder/hängender Wuchs", "herzförmige Blätter", "Blattunterseite rötlich"]',
  'Mexiko, Karibik', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'philodendron', 'POWO', true),

('Philodendron hederaceum', NULL, 'Philodendron', 'Araceae',
  '{"de": "Herzblatt-Philodendron", "en": "Heartleaf Philodendron"}',
  '["Philodendron scandens", "Philodendron oxycardium"]',
  '["herzförmige grüne Blätter", "kletternder/hängender Wuchs", "sehr robust", "häufigste Philodendron-Art"]',
  'Mexiko bis Brasilien', 'einfach', 'hell bis schattig', 'regelmäßig',
  'philodendron', 'POWO', true),

('Philodendron hastatum', NULL, 'Philodendron', 'Araceae',
  '{"de": "Silberschwert Philodendron", "en": "Silver Sword Philodendron"}',
  '["Philodendron hastatum Silver Sword"]',
  '["silbrig-blaue Blätter", "pfeilförmige Blätter", "kletternder Wuchs", "Blätter werden mit Alter größer und anders geformt"]',
  'Brasilien', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'philodendron', 'POWO', true),

('Philodendron mamei', NULL, 'Philodendron', 'Araceae',
  '{"de": "Mamei Philodendron", "en": "Mamei Philodendron"}',
  '[]',
  '["silbrig gemusterte Blätter", "kriechender Wuchs", "herzförmige Blätter"]',
  'Ecuador', 'mittel', 'hell bis halbschattig', 'regelmäßig',
  'philodendron', 'POWO', true),

('Philodendron plowmanii', NULL, 'Philodendron', 'Araceae',
  '{"de": "Plowmanii Philodendron", "en": "Plowmanii Philodendron"}',
  '[]',
  '["gewellter Blattrand", "kriechender Wuchs", "große Blätter", "grüne Farbe"]',
  'Peru, Ecuador', 'mittel', 'hell bis halbschattig', 'regelmäßig',
  'philodendron', 'POWO', true),

('Philodendron pastazanum', NULL, 'Philodendron', 'Araceae',
  '{"de": "Pastazanum Philodendron", "en": "Pastazanum Philodendron"}',
  '[]',
  '["große herzförmige Blätter", "kriechender Wuchs", "grüne Farbe"]',
  'Ecuador', 'mittel', 'hell bis halbschattig', 'regelmäßig',
  'philodendron', 'POWO', true),

('Philodendron gigas', NULL, 'Philodendron', 'Araceae',
  '{"de": "Riesen-Philodendron", "en": "Giant Philodendron"}',
  '[]',
  '["sehr große samtige Blätter", "kletternder Wuchs", "dunkelgrüne Farbe"]',
  'Panama', 'mittel', 'hell bis halbschattig', 'regelmäßig, hohe Luftfeuchtigkeit',
  'philodendron', 'POWO', true),

('Philodendron squamiferum', NULL, 'Philodendron', 'Araceae',
  '{"de": "Schuppenstieliger Philodendron", "en": "Hairy Philodendron"}',
  '[]',
  '["rote haarige Blattstiele", "tief eingeschnittene Blätter", "kletternder Wuchs"]',
  'Brasilien, Surinam', 'mittel', 'hell bis halbschattig', 'regelmäßig',
  'philodendron', 'POWO', true),

('Philodendron billietiae', NULL, 'Philodendron', 'Araceae',
  '{"de": "Billietiae Philodendron", "en": "Billietiae Philodendron"}',
  '[]',
  '["orange-gelbe Blattstiele", "lange schmale Blätter", "kletternder Wuchs"]',
  'Brasilien, Guyana', 'mittel', 'hell', 'regelmäßig',
  'philodendron', 'POWO', true),

('Philodendron atabapoense', NULL, 'Philodendron', 'Araceae',
  '{"de": "Atabapoense Philodendron", "en": "Atabapoense Philodendron"}',
  '[]',
  '["lange schmale Blätter", "Blattunterseite rötlich-violett", "kletternder Wuchs"]',
  'Venezuela, Brasilien', 'mittel', 'hell', 'regelmäßig',
  'philodendron', 'POWO', true),

('Philodendron spiritus sancti', NULL, 'Philodendron', 'Araceae',
  '{"de": "Heiliger Geist Philodendron", "en": "Spiritus Sancti Philodendron"}',
  '[]',
  '["extrem seltene Art", "schmale hängende Blätter", "kletternder Wuchs", "vom Aussterben bedroht"]',
  'Brasilien (Espírito Santo)', 'anspruchsvoll', 'hell', 'regelmäßig, hohe Luftfeuchtigkeit',
  'philodendron', 'POWO', true),

('Philodendron gloriosum x melanochrysum', 'El Choco Red', 'Philodendron', 'Araceae',
  '{"de": "El Choco Red Philodendron", "en": "El Choco Red Philodendron"}',
  '["Philodendron el choco red"]',
  '["samtige Blätter", "rötliche Unterseite", "kletternder Wuchs"]',
  'Züchtung', 'mittel', 'hell', 'regelmäßig',
  'philodendron', 'manual', true),

('Philodendron domesticum', 'Jose Buono', 'Philodendron', 'Araceae',
  '{"de": "Jose Buono Philodendron", "en": "Jose Buono Philodendron"}',
  '["Philodendron jose buono"]',
  '["große Blätter", "variegierte Formen mit weißen Flecken", "kletternder Wuchs"]',
  'Züchtung', 'mittel', 'hell', 'regelmäßig',
  'philodendron', 'manual', true)

ON DUPLICATE KEY UPDATE verified = verified;

-- ─── MONSTERA (10 Arten/Sorten) ───────────────────────────────────────────────
INSERT INTO taxonomy_species (scientificName, cultivar, genus, family, commonNames, synonyms, keyFeatures, habitat, careLevel, light, water, category, source, verified) VALUES
('Monstera deliciosa', NULL, 'Monstera', 'Araceae',
  '{"de": "Fensterblatt, Köstliche Monstera", "en": "Swiss Cheese Plant"}',
  '["Monstera deliciosa var. deliciosa"]',
  '["tief eingeschnittene Blätter mit Löchern", "kletternder Wuchs", "Luftwurzeln", "große grüne Blätter"]',
  'Mexiko bis Panama', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'monstera', 'POWO', true),

('Monstera deliciosa', 'Albo Variegata', 'Monstera', 'Araceae',
  '{"de": "Weißes Fensterblatt", "en": "Albo Monstera, White Monstera"}',
  '["Monstera deliciosa Albo", "Monstera albo variegata"]',
  '["weiße/cremefarbene Panaschierung", "tief eingeschnittene Blätter", "kletternder Wuchs", "ECHTE Panaschierung mit weißen Flecken/Sektoren"]',
  'Züchtung', 'anspruchsvoll', 'hell', 'regelmäßig',
  'monstera', 'manual', true),

('Monstera deliciosa', 'Thai Constellation', 'Monstera', 'Araceae',
  '{"de": "Thai Constellation Monstera", "en": "Thai Constellation Monstera"}',
  '[]',
  '["cremefarbene Panaschierung mit Sternenmuster", "tief eingeschnittene Blätter", "kletternder Wuchs", "stabile Panaschierung"]',
  'Züchtung (Thailand)', 'mittel', 'hell', 'regelmäßig',
  'monstera', 'manual', true),

('Monstera adansonii', NULL, 'Monstera', 'Araceae',
  '{"de": "Adansonii Monstera, Schweizer Käse Rebe", "en": "Swiss Cheese Vine"}',
  '["Monstera friedrichsthalii"]',
  '["ovale Blätter mit Löchern", "kletternder/hängender Wuchs", "kleinere Blätter als M. deliciosa"]',
  'Mittel- und Südamerika', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'monstera', 'POWO', true),

('Monstera adansonii', 'Variegata', 'Monstera', 'Araceae',
  '{"de": "Variegierte Adansonii", "en": "Variegated Swiss Cheese Vine"}',
  '[]',
  '["ovale Blätter mit Löchern", "weiße/cremefarbene Panaschierung", "kletternder Wuchs"]',
  'Züchtung', 'anspruchsvoll', 'hell', 'regelmäßig',
  'monstera', 'manual', true),

('Monstera obliqua', NULL, 'Monstera', 'Araceae',
  '{"de": "Obliqua Monstera", "en": "Obliqua Monstera"}',
  '[]',
  '["sehr viele Löcher (mehr Loch als Blatt)", "extrem selten", "kletternder Wuchs", "zarte dünne Blätter"]',
  'Südamerika', 'anspruchsvoll', 'hell', 'regelmäßig, hohe Luftfeuchtigkeit',
  'monstera', 'POWO', true),

('Monstera siltepecana', NULL, 'Monstera', 'Araceae',
  '{"de": "Silberne Monstera", "en": "Silver Monstera"}',
  '[]',
  '["silbrig-grüne Blätter als Jungpflanze", "kletternder Wuchs", "Blattform ändert sich mit Alter"]',
  'Mexiko, Mittelamerika', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'monstera', 'POWO', true),

('Monstera standleyana', NULL, 'Monstera', 'Araceae',
  '{"de": "Standleyana Monstera", "en": "Standleyana Monstera"}',
  '["Philodendron cobanum"]',
  '["ovale Blätter ohne Löcher", "kletternder Wuchs", "variegierte Formen verfügbar"]',
  'Mittelamerika', 'einfach', 'hell bis halbschattig', 'regelmäßig',
  'monstera', 'POWO', true),

('Monstera dubia', NULL, 'Monstera', 'Araceae',
  '{"de": "Dubia Monstera", "en": "Dubia Monstera"}',
  '[]',
  '["Jungpflanze kriecht an Baumstämmen", "Blätter wechseln Form mit Alter", "silbrig gemusterte Jungblätter"]',
  'Mittel- und Südamerika', 'mittel', 'hell', 'regelmäßig',
  'monstera', 'POWO', true),

('Monstera pinnatipartita', NULL, 'Monstera', 'Araceae',
  '{"de": "Pinnatipartita Monstera", "en": "Pinnatipartita Monstera"}',
  '[]',
  '["tief eingeschnittene Blätter", "kletternder Wuchs", "Blätter werden mit Alter größer"]',
  'Kolumbien, Peru', 'mittel', 'hell bis halbschattig', 'regelmäßig',
  'monstera', 'POWO', true)

ON DUPLICATE KEY UPDATE verified = verified;

-- ─── AQUARIENPFLANZEN (20 Arten) ──────────────────────────────────────────────
INSERT INTO taxonomy_species (scientificName, cultivar, genus, family, commonNames, synonyms, keyFeatures, habitat, careLevel, light, water, category, source, verified) VALUES
('Bucephalandra sp.', NULL, 'Bucephalandra', 'Araceae',
  '{"de": "Bucephalandra", "en": "Bucephalandra"}',
  '[]',
  '["kleine Wasserpflanze", "auf Steinen/Holz befestigbar", "diverse Formen und Farben", "langsames Wachstum"]',
  'Borneo, Bachläufe', 'mittel', 'schwach bis mittel', 'weiches, leicht saures Wasser',
  'aquatic', 'manual', true),

('Anubias barteri', NULL, 'Anubias', 'Araceae',
  '{"de": "Anubias", "en": "Anubias"}',
  '["Anubias barteri var. barteri"]',
  '["breite dunkelgrüne Blätter", "auf Steinen/Holz befestigbar", "langsames Wachstum", "robust"]',
  'Westafrika, Bachläufe', 'einfach', 'schwach bis mittel', 'variabel',
  'aquatic', 'POWO', true),

('Anubias barteri', 'Nana', 'Anubias', 'Araceae',
  '{"de": "Zwerg-Anubias", "en": "Dwarf Anubias"}',
  '["Anubias nana", "Anubias barteri var. nana"]',
  '["kleine runde Blätter", "Zwergform", "auf Steinen/Holz befestigbar", "sehr robust"]',
  'Westafrika', 'einfach', 'schwach bis mittel', 'variabel',
  'aquatic', 'POWO', true),

('Anubias barteri', 'Nana Petite', 'Anubias', 'Araceae',
  '{"de": "Petite Zwerg-Anubias", "en": "Petite Dwarf Anubias"}',
  '["Anubias nana petite"]',
  '["sehr kleine Blätter", "Miniaturform", "auf Steinen/Holz befestigbar"]',
  'Züchtung', 'einfach', 'schwach bis mittel', 'variabel',
  'aquatic', 'manual', true),

('Cryptocoryne wendtii', NULL, 'Cryptocoryne', 'Araceae',
  '{"de": "Wendts Wasserkelch", "en": "Wendt Crypt"}',
  '[]',
  '["rosettenwüchsig", "braun-grüne Blätter", "robust", "Bodenpflanze"]',
  'Sri Lanka', 'einfach', 'schwach bis mittel', 'variabel',
  'aquatic', 'POWO', true),

('Cryptocoryne parva', NULL, 'Cryptocoryne', 'Araceae',
  '{"de": "Zwerg-Wasserkelch", "en": "Dwarf Crypt"}',
  '[]',
  '["sehr kleine Rosette", "grüne Blätter", "Bodenpflanze", "langsames Wachstum"]',
  'Sri Lanka', 'einfach', 'schwach bis mittel', 'variabel',
  'aquatic', 'POWO', true),

('Cryptocoryne balansae', NULL, 'Cryptocoryne', 'Araceae',
  '{"de": "Balansa Wasserkelch", "en": "Balansa Crypt"}',
  '[]',
  '["lange schmale Blätter", "stark gewellter Blattrand", "Bodenpflanze"]',
  'Thailand, Vietnam', 'einfach', 'schwach bis mittel', 'weiches Wasser',
  'aquatic', 'POWO', true),

('Cryptocoryne undulata', NULL, 'Cryptocoryne', 'Araceae',
  '{"de": "Gewellter Wasserkelch", "en": "Undulate Crypt"}',
  '[]',
  '["gewellte Blätter", "braun-grüne Farbe", "Bodenpflanze"]',
  'Sri Lanka', 'einfach', 'schwach bis mittel', 'variabel',
  'aquatic', 'POWO', true),

('Microsorum pteropus', NULL, 'Microsorum', 'Polypodiaceae',
  '{"de": "Javafarn", "en": "Java Fern"}',
  '["Leptochilus pteropus"]',
  '["auf Steinen/Holz befestigbar", "grüne Blätter", "langsames Wachstum", "robust"]',
  'Südostasien', 'einfach', 'schwach bis mittel', 'variabel',
  'aquatic', 'POWO', true),

('Taxiphyllum barbieri', NULL, 'Taxiphyllum', 'Hypnaceae',
  '{"de": "Javamoos", "en": "Java Moss"}',
  '["Vesicularia dubyana (falsch zugeordnet)"]',
  '["Moos", "auf Steinen/Holz befestigbar", "dichtes Wachstum", "robust"]',
  'Südostasien', 'einfach', 'schwach bis mittel', 'variabel',
  'aquatic', 'POWO', true),

('Vesicularia dubyana', NULL, 'Vesicularia', 'Hypnaceae',
  '{"de": "Weihnachtsmoos", "en": "Christmas Moss"}',
  '[]',
  '["Moos mit weihnachtsbaumartiger Struktur", "auf Steinen/Holz befestigbar"]',
  'Südostasien', 'einfach', 'schwach bis mittel', 'variabel',
  'aquatic', 'POWO', true),

('Hemianthus callitrichoides', NULL, 'Hemianthus', 'Linderniaceae',
  '{"de": "Kuba-Perlkraut", "en": "Dwarf Baby Tears, HC Cuba"}',
  '["HC Cuba"]',
  '["sehr kleine Blätter", "Bodendecker", "dichtes Wachstum", "anspruchsvoll"]',
  'Kuba', 'anspruchsvoll', 'stark', 'weiches, CO2-angereichertes Wasser',
  'aquatic', 'POWO', true),

('Eleocharis acicularis', NULL, 'Eleocharis', 'Cyperaceae',
  '{"de": "Nadelsimse, Haargras", "en": "Needle Spike-rush, Hair Grass"}',
  '[]',
  '["grasartige Pflanze", "Bodendecker", "grüne Halme"]',
  'Weltweit verbreitet', 'mittel', 'mittel bis stark', 'variabel',
  'aquatic', 'POWO', true),

('Rotala rotundifolia', NULL, 'Rotala', 'Lythraceae',
  '{"de": "Runde Rotala", "en": "Roundleaf Toothcup"}',
  '[]',
  '["rötliche Stängelpflanze", "kleine runde Blätter", "Mittelgrundpflanze"]',
  'Südostasien', 'einfach', 'mittel bis stark', 'weiches Wasser',
  'aquatic', 'POWO', true),

('Ludwigia repens', NULL, 'Ludwigia', 'Onagraceae',
  '{"de": "Kriechende Ludwigia", "en": "Creeping Primrose-willow"}',
  '[]',
  '["rötliche Blätter", "Stängelpflanze", "Hintergrundpflanze"]',
  'Nordamerika', 'einfach', 'mittel bis stark', 'variabel',
  'aquatic', 'POWO', true),

('Alternanthera reineckii', NULL, 'Alternanthera', 'Amaranthaceae',
  '{"de": "Papageienblatt", "en": "Reineck Alternanthera"}',
  '[]',
  '["rote bis violette Blätter", "Stängelpflanze", "Hintergrundpflanze"]',
  'Südamerika', 'mittel', 'stark', 'weiches Wasser',
  'aquatic', 'POWO', true),

('Pogostemon helferi', NULL, 'Pogostemon', 'Lamiaceae',
  '{"de": "Downoi, Kleiner Stern", "en": "Downoi, Little Star Plant"}',
  '["Downoi"]',
  '["sternförmige Blätter", "Vordergrundpflanze", "gewellte Blattränder"]',
  'Thailand, Myanmar', 'mittel', 'stark', 'weiches, saures Wasser',
  'aquatic', 'POWO', true),

('Hygrophila pinnatifida', NULL, 'Hygrophila', 'Acanthaceae',
  '{"de": "Fiederspaltige Hygrophila", "en": "Pinnatifida Hygrophila"}',
  '[]',
  '["tief eingeschnittene Blätter", "braun-rötliche Farbe", "auf Steinen/Holz befestigbar"]',
  'Indien', 'mittel', 'mittel bis stark', 'variabel',
  'aquatic', 'POWO', true),

('Bolbitis heudelotii', NULL, 'Bolbitis', 'Dryopteridaceae',
  '{"de": "Afrikanischer Wasserfarn", "en": "African Water Fern"}',
  '[]',
  '["dunkelgrüner Farn", "auf Steinen/Holz befestigbar", "langsames Wachstum"]',
  'Westafrika', 'mittel', 'schwach bis mittel', 'weiches, saures Wasser',
  'aquatic', 'POWO', true),

('Vallisneria spiralis', NULL, 'Vallisneria', 'Hydrocharitaceae',
  '{"de": "Schraubenvallisnerie", "en": "Straight Vallisneria"}',
  '[]',
  '["lange bandförmige Blätter", "Hintergrundpflanze", "robust", "schnelles Wachstum"]',
  'Europa, Asien, Afrika', 'einfach', 'mittel bis stark', 'hartes Wasser',
  'aquatic', 'POWO', true)

ON DUPLICATE KEY UPDATE verified = verified;

-- ─── CHANNA (15 Arten) ────────────────────────────────────────────────────────
INSERT INTO taxonomy_species (scientificName, cultivar, genus, family, commonNames, synonyms, keyFeatures, habitat, careLevel, light, water, category, source, verified) VALUES
('Channa andrao', NULL, 'Channa', 'Channidae',
  '{"de": "Andraos Schlangenkopf", "en": "Andrao Snakehead"}',
  '[]',
  '["leuchtend orange-rote Flossen", "kompakter Körperbau", "Zwergschlangenkopf", "max. 15-20cm"]',
  'Bangladesch, Indien (Assam)', 'mittel', NULL, 'weiches, saures Wasser, Blackwater',
  'channa', 'FishBase', true),

('Channa asiatica', NULL, 'Channa', 'Channidae',
  '{"de": "Chinesischer Schlangenkopf", "en": "Small Snakehead"}',
  '[]',
  '["grün-braune Musterung", "mittlere Größe", "max. 35cm"]',
  'China, Vietnam', 'mittel', NULL, 'variabel',
  'channa', 'FishBase', true),

('Channa aurantimaculata', NULL, 'Channa', 'Channidae',
  '{"de": "Orangeflecken-Schlangenkopf", "en": "Orange-spotted Snakehead"}',
  '[]',
  '["orange Flecken auf dunklem Körper", "leuchtende Flossen", "max. 40cm"]',
  'Indien (Assam, Brahmaputra)', 'mittel', NULL, 'weiches, kühles Wasser',
  'channa', 'FishBase', true),

('Channa barca', NULL, 'Channa', 'Channidae',
  '{"de": "Barca Schlangenkopf", "en": "Barca Snakehead"}',
  '[]',
  '["auffällige Musterung", "große Art", "max. 90cm", "Tigermuster"]',
  'Indien, Bangladesch', 'anspruchsvoll', NULL, 'weiches Wasser',
  'channa', 'FishBase', true),

('Channa bleheri', NULL, 'Channa', 'Channidae',
  '{"de": "Blehers Schlangenkopf, Regenbogen-Schlangenkopf", "en": "Rainbow Snakehead"}',
  '[]',
  '["leuchtend bunte Flossen (rot, blau, orange)", "Zwergschlangenkopf", "max. 20cm", "kühle Temperaturen bevorzugt"]',
  'Indien (Assam)', 'mittel', NULL, 'weiches, kühles Wasser',
  'channa', 'FishBase', true),

('Channa diplogramma', NULL, 'Channa', 'Channidae',
  '{"de": "Malabar-Schlangenkopf", "en": "Malabar Snakehead"}',
  '["Channa diplogramma"]',
  '["große Art", "max. 60cm", "braun-grüne Musterung"]',
  'Indien (Kerala)', 'mittel', NULL, 'variabel',
  'channa', 'FishBase', true),

('Channa gachua', NULL, 'Channa', 'Channidae',
  '{"de": "Zwerg-Schlangenkopf", "en": "Dwarf Snakehead"}',
  '[]',
  '["Zwergschlangenkopf", "max. 20cm", "variable Färbung je nach Herkunft", "bunte Flossen"]',
  'Süd- und Südostasien', 'einfach', NULL, 'variabel',
  'channa', 'FishBase', true),

('Channa limbata', NULL, 'Channa', 'Channidae',
  '{"de": "Gesäumter Schlangenkopf", "en": "Limbata Snakehead"}',
  '[]',
  '["orange gesäumte Flossen", "Zwergschlangenkopf", "max. 20cm"]',
  'Südostasien', 'einfach', NULL, 'weiches Wasser',
  'channa', 'FishBase', true),

('Channa lucius', NULL, 'Channa', 'Channidae',
  '{"de": "Hecht-Schlangenkopf", "en": "Splendid Snakehead"}',
  '[]',
  '["schlanker Körperbau", "max. 40cm", "grün-braune Musterung"]',
  'Südostasien', 'mittel', NULL, 'weiches, saures Wasser',
  'channa', 'FishBase', true),

('Channa marulioides', NULL, 'Channa', 'Channidae',
  '{"de": "Kaiser-Schlangenkopf", "en": "Emperor Snakehead"}',
  '[]',
  '["große Art", "max. 65cm", "auffällige Musterung"]',
  'Südostasien', 'anspruchsvoll', NULL, 'variabel',
  'channa', 'FishBase', true),

('Channa micropeltes', NULL, 'Channa', 'Channidae',
  '{"de": "Riesenschlangenkopf", "en": "Giant Snakehead"}',
  '[]',
  '["größte Channa-Art", "max. 130cm", "Jungtiere rot-schwarz gestreift", "Adulte grün-schwarz"]',
  'Südostasien', 'anspruchsvoll', NULL, 'variabel',
  'channa', 'FishBase', true),

('Channa ornatipinnis', NULL, 'Channa', 'Channidae',
  '{"de": "Schmuckflossen-Schlangenkopf", "en": "Ornate Snakehead"}',
  '[]',
  '["leuchtend bunte Flossen", "Zwergschlangenkopf", "max. 20cm"]',
  'Zentralafrika', 'mittel', NULL, 'weiches, saures Wasser',
  'channa', 'FishBase', true),

('Channa pulchra', NULL, 'Channa', 'Channidae',
  '{"de": "Schöner Schlangenkopf", "en": "Beautiful Snakehead"}',
  '[]',
  '["leuchtend blaue Flossen", "Zwergschlangenkopf", "max. 25cm", "kühle Temperaturen"]',
  'Myanmar', 'mittel', NULL, 'weiches, kühles Wasser',
  'channa', 'FishBase', true),

('Channa stewartii', NULL, 'Channa', 'Channidae',
  '{"de": "Stewarts Schlangenkopf", "en": "Stewart Snakehead"}',
  '[]',
  '["orange-rote Flossen", "Zwergschlangenkopf", "max. 20cm", "kühle Temperaturen"]',
  'Indien (Assam, Brahmaputra)', 'mittel', NULL, 'weiches, kühles Wasser',
  'channa', 'FishBase', true),

('Channa striata', NULL, 'Channa', 'Channidae',
  '{"de": "Gestreifter Schlangenkopf", "en": "Striped Snakehead"}',
  '[]',
  '["gestreifte Musterung", "mittlere bis große Art", "max. 90cm", "weit verbreitet"]',
  'Süd- und Südostasien', 'einfach', NULL, 'variabel',
  'channa', 'FishBase', true)

ON DUPLICATE KEY UPDATE verified = verified;

-- ─── KI-HALLUZINATIONS-BLACKLIST ──────────────────────────────────────────────
INSERT INTO ai_hallucination_blacklist (term, reason, correctAlternative) VALUES
('Fredek Varigata', 'Nicht-existente Sorte. Halluzination des LLM. Korrekte Sorte wäre Alocasia micholitziana Frydek (ohne Variegata bei Normalform).', 'Alocasia micholitziana Frydek'),
('Fredek Variegata', 'Nicht-existente Sorte. Halluzination des LLM.', 'Alocasia micholitziana Frydek'),
('Alocasia Fredek Varigata', 'Nicht-existente Sorte.', 'Alocasia micholitziana Frydek'),
('Alocasia Fredek Variegata', 'Nicht-existente Sorte.', 'Alocasia micholitziana Frydek'),
('Dragon''s Tooth', 'Nicht-existente Sorte. Halluzination des LLM. Es gibt Dragon Scale (Alocasia baginda), aber KEIN Dragon''s Tooth.', 'Alocasia baginda Dragon Scale'),
('Alocasia Dragon''s Tooth', 'Nicht-existente Sorte.', 'Alocasia baginda Dragon Scale'),
('Alocasia baginda Dragon''s Tooth', 'Nicht-existente Sorte. Nur Dragon Scale und Silver Dragon existieren bei Alocasia baginda.', 'Alocasia baginda Dragon Scale'),
('Alocasia longiloba Silver', 'Falsche Zuordnung für Drachenschuppen-Muster. Drachenschuppen ist Alocasia baginda Dragon Scale, nicht longiloba.', 'Alocasia baginda Dragon Scale'),
('Philodendron Florida Beauty Variegata', 'Korrekte Bezeichnung ist Philodendron pedatum Florida Beauty (variegierte Form). Nicht als eigenständige Art.', 'Philodendron pedatum Florida Beauty')

ON DUPLICATE KEY UPDATE reason = VALUES(reason);
